# Generated by Django 4.2.8 on 2024-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='address',
            field=models.CharField(max_length=120),
        ),
    ]
