# Generated by Django 4.2.8 on 2024-01-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0002_remove_contactinformation_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
