# Generated by Django 4.2.8 on 2024-01-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0004_userprofile_bio_userprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
