# Generated by Django 4.2.8 on 2024-01-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0005_remove_userprofile_bio_remove_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
