# Generated by Django 4.2.8 on 2024-01-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0008_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
