# Generated by Django 5.0.1 on 2024-01-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0012_stockdata_delete_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='high_price',
            new_name='ema',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volume',
        ),
    ]
