# Generated by Django 4.2.8 on 2024-01-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0014_stockdata_rs_stockdata_rsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='ema',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='rs',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='rsi',
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='IndicatorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ema20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema50', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema100', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ema200', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.stockdata')),
            ],
        ),
    ]
