# Generated by Django 4.2.8 on 2024-01-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0017_userprofile_email_verified_userprofile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
    ]
