# Generated by Django 5.0.1 on 2024-01-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0018_remove_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ema20_count', models.IntegerField(default=0)),
                ('ema50_count', models.IntegerField(default=0)),
                ('ema100_count', models.IntegerField(default=0)),
                ('ema200_count', models.IntegerField(default=0)),
                ('stock_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.stockdata')),
            ],
        ),
    ]
