# Generated by Django 5.0.1 on 2024-01-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0019_indicatorcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorCount',
        ),
    ]
