# Generated by Django 5.0.1 on 2024-01-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0020_delete_indicatorcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmaCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ema20_count', models.IntegerField(default=0)),
                ('ema50_count', models.IntegerField(default=0)),
                ('ema100_count', models.IntegerField(default=0)),
                ('ema200_count', models.IntegerField(default=0)),
                ('ema20_prev_state_positive', models.BooleanField(default=True)),
                ('ema50_prev_state_positive', models.BooleanField(default=True)),
                ('ema100_prev_state_positive', models.BooleanField(default=True)),
                ('ema200_prev_state_positive', models.BooleanField(default=True)),
                ('stock_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.stockdata')),
            ],
        ),
    ]
