# Generated by Django 5.0.1 on 2024-01-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0021_emacounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emacounts',
            name='ema100_prev_state_positive',
        ),
        migrations.RemoveField(
            model_name='emacounts',
            name='ema200_prev_state_positive',
        ),
        migrations.RemoveField(
            model_name='emacounts',
            name='ema20_prev_state_positive',
        ),
        migrations.RemoveField(
            model_name='emacounts',
            name='ema50_prev_state_positive',
        ),
    ]
