# Generated by Django 5.0.1 on 2024-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0024_financialdata_alter_emacounts_stock_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emacounts',
            name='ema100_output',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emacounts',
            name='ema200_output',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emacounts',
            name='ema20_output',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emacounts',
            name='ema50_output',
            field=models.IntegerField(),
        ),
    ]
