# Generated by Django 5.0.1 on 2024-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0025_alter_emacounts_ema100_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emacounts',
            name='rs_output',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emacounts',
            name='rsi_output',
            field=models.IntegerField(null=True),
        ),
    ]
