# Generated by Django 5.0.1 on 2024-02-08 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0027_sectordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmaCountsSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ema20_output', models.IntegerField()),
                ('ema50_output', models.IntegerField()),
                ('ema100_output', models.IntegerField()),
                ('ema200_output', models.IntegerField()),
                ('rsi_output', models.IntegerField(null=True)),
                ('rs_output', models.IntegerField(null=True)),
                ('stock_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.financialdata')),
            ],
        ),
    ]
