# Generated by Django 5.0.1 on 2024-02-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0028_emacountssector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emacountssector',
            name='stock_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocks.sectordata'),
        ),
    ]
