# Generated by Django 3.2.23 on 2024-02-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0030_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_user',
            name='watchlist_sector',
        ),
        migrations.AddField(
            model_name='stock_user',
            name='watchlist_sector',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='stock_user',
            name='watchlist_stock',
        ),
        migrations.AddField(
            model_name='stock_user',
            name='watchlist_stock',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
