# Generated by Django 5.0.3 on 2024-03-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0031_auto_20240221_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_user',
            name='watchlist_stock',
        ),
    ]
