# Generated by Django 5.0.3 on 2024-04-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0033_alter_stock_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_user',
            name='closePosition',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='stock_user',
            name='portfolio',
            field=models.TextField(default='[]'),
        ),
    ]
