# Generated by Django 5.0.3 on 2024-04-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0034_stock_user_closeposition_stock_user_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('sector_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('isincode', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('isincode', models.CharField(max_length=255)),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('sectors', models.ManyToManyField(to='Stocks.sectors')),
            ],
        ),
    ]
