# Generated by Django 5.0.3 on 2024-05-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0035_sectors_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='address',
            new_name='message',
        ),
    ]
