# Generated by Django 5.0.3 on 2024-05-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0036_rename_address_contactinformation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='Stocks.sectors'),
        ),
    ]
