# Generated by Django 5.0.2 on 2024-05-03 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0037_alert_main'),
        ('Stocks', '0038_alter_stocks_sectors'),
    ]

    operations = [
    ]
